	<div class="modal_list sitemap_modal clearfix">
		<input type="text" value="Start typing to refine your options" id="sitemap_filter_input" class="search_field filter_bg">
		<div class="modal_list_column">
			<a class="modal_titles" href="/vascular/about/">About the Center</a>
			<ul class="section_nav">
				<li><a href="/vascular/about/">Mission Statement</a></li>
				<li><a href="/vascular/about/history_of_vascular_biology_at_weill_cornell.html">History of Vascular Biology at Weill Cornell</a></li>
				<li><a href="/vascular/about/current_research_strengths.html">Current Research Strengths</a></li>
				<li><a href="/vascular/about/seminars.html">Seminars</a></li>
				<li><a href="/vascular/about/news_and_events.html">News and Events</a></li>
			</ul>
			<a class="modal_titles" href="/vascular/faculty/">Faculty</a>
			<ul class="section_nav">
				<li><a href="/vascular/faculty/internal_advisory_committee.html">Internal Advisory Committee</a></li>
			</ul>
		</div>
		<div class="modal_list_column">
			<a class="modal_titles" href="/vascular/research/">Research</a>
			<ul class="section_nav">
				<li><a href="/vascular/research/">Vascular Cell and Molecular Biology</a></li>
				<li><a href="/vascular/research/mechanisms_of_angiogenesis_and_vasculogenesis.html">Mechanisms of Angiogenesis and Vasculogenesis</a></li>
				<li><a href="/vascular/research/stem_or_progenitor_cells_in_the_vascular_system.html">Stem/Progenitor Cells in the Vascular System</a></li>
				<li><a href="/vascular/research/lipid_mediators_and_cell_signaling.html">Lipid Mediators and Cell Signaling</a></li>
				<li><a href="/vascular/research/mechanisms_of_metastasis.html">Mechanisms of Metastasis</a></li>
				<li><a href="/vascular/research/platelet_biology.html">Platelet Biology</a></li>
				<li><a href="/vascular/research/hypertensive_vascular_disease.html">Hypertensive Vascular Disease</a></li>
			</ul>
			<a class="modal_titles" href="/vascular/protocols_and_downloads/">Protocols/Downloads</a>
			<ul class="section_nav">
			</ul>
		</div>
		<div class="modal_list_column last">
			<a class="modal_titles" href="/vascular/training/">Training</a>
			<ul class="section_nav">
				<li><a href="/vascular/training/current_postdoctoral_trainees.html">Current Postdoctoral Trainees</a></li>
				<li><a href="/vascular/training/t32_training_grant.html">T32 Training Grant</a></li>
				<li><a href="/vascular/training/academic_training_in_vascular_biology.html">Academic Training in Vascular Biology</a></li>
			</ul>
		</div>
	</div>